---
- name: Verificar montaje NFS en frontends
  shell: "mount | grep '/var/www/html/media'"
  when: inventory_hostname in groups['frontend']
  register: nfs_mount
  failed_when: nfs_mount.rc != 0



- name: Mostrar estado del montaje
  debug:
    var: nfs_mounted.stdout

- name: Falla si el directorio NFS no está montado
  fail:
    msg: "NFS no está montado en este frontend"
  when: nfs_mounted.stdout == ""

- name: OK
  debug:
    msg: "NFS montado correctamente"
