---
- name: Desplegar app PHP para la clínica en Frontends
  hosts: frontend1,frontend2
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: Crear directorio de la app
      file:
        path: "{{ directories.app }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Crear archivo config.php
      copy:
        dest: "{{ directories.app }}/config.php"
        content: |
          <?php
          $host = "{{ ip.backend1 }}";
          $dbname = "{{ db.name }}";
          $user = "{{ db.user }}";
          $pass = "{{ db.password }}";

          try {
              $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8", $user, $pass);
              $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
          } catch (PDOException $e) {
              die("Error de conexión: " . $e->getMessage());
          }
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Crear archivo index.php
      copy:
        src: ../templates/app_index.php
        dest: "{{ directories.app }}/index.php"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
