---
- name: Desplegar app PHP para la cl√≠nica en Frontends
  hosts: frontend1,frontend2
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Crear directorio web si no existe
      file:
        path: "{{ directories.web }}"
        state: directory
        mode: '0755'

    - name: Crear directorio de la app si no existe
      file:
        path: "{{ directories.app }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copiar config.php
      template:
        src: ../templates/config.php.j2
        dest: "{{ directories.web }}/config.php"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Copiar index.php de la app
      copy:
        src: ../templates/app_index.php
        dest: "{{ directories.web }}/index.php"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
