---
- name: Setup Load Balancer
  hosts: loadbalancer
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Instalar nginx
      apt:
        name: nginx
        state: present

    - name: Copiar config de load balancer
      template:
        src: "../templates/loadbalancer.conf.j2"
        dest: "/etc/nginx/sites-available/clinica_lb.conf"

    - name: Activar LB
      file:
        src: /etc/nginx/sites-available/clinica_lb.conf
        dest: /etc/nginx/sites-enabled/clinica_lb.conf
        state: link
      ignore_errors: yes

    - name: Reiniciar nginx
      systemd:
        name: nginx
        state: restarted
