---
- name: Setup Apache, PHP and Session Handler Configuration
  hosts: frontend
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Install Apache and required PHP packages
      apt:
        name:
          - apache2
          - php
          - php-cli
          - php-mysql
          - php-json
          - php-xml
          - php-mbstring
          - libapache2-mod-php
          - php-gd
          - php-curl
          - php-zip
          - php-intl
        state: present
        update_cache: yes

    - name: Enable PHP module
      command: a2enmod php8.3
      ignore_errors: yes

    - name: Configure Default VirtualHost
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              DocumentRoot /var/www/html

              <Directory /var/www/html>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
      notify: restart_apache

    - name: Update php.ini for session handler
      template:
        src: ../templates/php.ini.j2
        dest: /etc/php/8.3/apache2/php.ini
      notify: restart_apache

  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted
