---
- name: Configurar Nginx como balanceador de carga
  hosts: lb
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Instalar nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Asegurar que /etc/nginx existe
      file:
        path: /etc/nginx
        state: directory
        mode: "0755"

    - name: Crear nginx.conf base si no existe
      copy:
        dest: /etc/nginx/nginx.conf
        force: no
        mode: "0644"
        content: |
          user www-data;
          worker_processes auto;
          pid /run/nginx.pid;
          include /etc/nginx/modules-enabled/*.conf;

          events {
              worker_connections 768;
          }

          http {
              sendfile on;
              tcp_nopush on;
              types_hash_max_size 2048;

              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              keepalive_timeout 65;

              include /etc/nginx/conf.d/*.conf;
              include /etc/nginx/sites-enabled/*;
          }

    - name: Copiar configuraci√≥n del balanceador
      template:
        src: "../templates/loadbalancer.conf.j2"
        dest: "{{ lb_nginx_conf_path }}"
        mode: "0644"

    - name: Eliminar sitio default de nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Recargar Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
