---
- name: Configurar Load Balancer con NGINX
  hosts: loadbalancer
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Actualizar sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Instalar NGINX
      apt:
        name: nginx
        state: present

    - name: Deshabilitar virtualhost por defecto
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copiar configuración del Load Balancer
      template:
        src: "../templates/loadbalancer.conf.j2"
        dest: /etc/nginx/sites-available/loadbalancer.conf
        owner: root
        group: root
        mode: "0644"

    - name: Habilitar configuración del Load Balancer
      file:
        src: /etc/nginx/sites-available/loadbalancer.conf
        dest: /etc/nginx/sites-enabled/loadbalancer.conf
        state: link
        force: yes

    - name: Probar configuración de NGINX
      command: nginx -t
      register: nginx_test
      ignore_errors: no

    - name: Reiniciar NGINX
      service:
        name: nginx
        state: restarted
