---
- hosts: lb
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Instalar nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Asegurar que /etc/nginx existe
      file:
        path: /etc/nginx
        state: directory

    - name: Crear nginx.conf estándar (no tocar)
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user www-data;
          worker_processes auto;
          pid /run/nginx.pid;

          events {
              worker_connections 768;
          }

          http {
              include       /etc/nginx/mime.types;
              default_type  application/octet-stream;

              sendfile        on;
              keepalive_timeout 65;

              include /etc/nginx/sites-enabled/*;
          }

    - name: Crear configuración del balanceador
      template:
        src: templates/loadbalancer.conf.j2
        dest: /etc/nginx/sites-available/clinica_lb.conf

    - name: Activar sitio
      file:
        src: /etc/nginx/sites-available/clinica_lb.conf
        dest: /etc/nginx/sites-enabled/clinica_lb.conf
        state: link
        force: yes

    - name: Eliminar default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Recargar nginx
      service:
        name: nginx
        state: restarted
