---
- name: Configurar Nginx como load balancer
  hosts: loadbalancer
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: Instalar nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copiar config del load balancer
      template:
        src: "{{ templates_dir }}/loadbalancer.conf.j2"
        dest: "{{ lb_nginx_conf_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Eliminar default de nginx si existe
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Probar configuraci√≥n de nginx
      command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: nginx_test.rc != 0

    - name: Recargar nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
