- name: Configurar Load Balancer
  hosts: loadbalancer
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: Instalar Nginx si no está
      apt:
        name: nginx
        state: present

    - name: Deshabilitar virtualhost por defecto
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copiar configuración de Load Balancer
      template:
        src: ../templates/loadbalancer.conf.j2
        dest: /etc/nginx/sites-available/loadbalancer.conf

    - name: Habilitar sitio
      file:
        src: /etc/nginx/sites-available/loadbalancer.conf
        dest: /etc/nginx/sites-enabled/loadbalancer.conf
        state: link

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
