---
- name: Configurar Frontend
  hosts: frontend1,frontend2
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Actualizar repositorios
      apt:
        update_cache: yes

    - name: Instalar Apache y PHP si no están
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Habilitar módulo rewrite de Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Crear directorio web si no existe
      file:
        path: "{{ directories.web }}"
        state: directory
        mode: '0755'

    - name: Copiar VirtualHost desde template
      template:
        src: ../templates/app.conf.j2
        dest: /etc/apache2/sites-available/app.conf
        mode: '0644'

    - name: Activar VirtualHost app.conf
      file:
        src: /etc/apache2/sites-available/app.conf
        dest: /etc/apache2/sites-enabled/app.conf
        state: link
        force: yes

    - name: Deshabilitar sitio por defecto
      file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent

    - name: Copiar index.php de la app
      copy:
        src: ../templates/app_index.php
        dest: "{{ directories.web }}/index.php"
        mode: '0644'

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
